### ISSUE TITLE
 office-31 demo doesn't work 

### ISSUE THREAD

**Issue by PussInCode** [median-research-group/LibMTL#12]
I ran the demo of office-31and found some errors in this example:
The version of pip is not the same version published on github
The operating environment is as follows：
- python = 3.8
- pytroch = 1.12

In train.py,  .next() can't run
![image](https://user-images.githubusercontent.com/38970840/178885678-45bb27fa-4300-4581-bde9-25f2804d510a.png)

After I modified this syntax, the new problem appeared again
` data = data.to(self.device, non_blocking=True)` 

I want to know if this is a version reason or something else

**Comment by Baijiong-Lin** [comment]
The environment we used is as follows:

- Python == 3.8.3
- torch ==1.8.1+cu111
- torchvision == 0.9.1+cu111

and it can work.

> The version of pip is not the same version published on github

Yes. The code on github is lastest. We will release the lastest version on PyPi soon.

**Comment by Baijiong-Lin** [comment]
Actually, I don't understand your question and I hope you can clarify it or give some examples. In fact, ``Encoder`` here must be a class, not an instantiated object, but ``decoders`` is the opposite.

**Comment by PussInCode** [comment]
Yes,I didn't express it very clearly 
I wondered if it was possible not to use `Encoder `and  `decoders ` class
Because not all models have to be encoded and decoded

**Comment by Baijiong-Lin** [comment]
``encoder_class`` and ``decoders`` are used to define the network architecture of the model and they are necessary. 

The meanings of ``encoder_class`` and ``decoders`` may be more general.  For example, in the hard-parameter sharing pattern, ``encoder_class`` represents the task-sharing parameters (usually the feature extractor in cv problems), and ``decoders`` denotes the task-specific parameters (usually the output modules).

**Comment by Sakura4036** [comment]
In train.py, .next() can't run

I got a same error! -> "AttributeError: 'dict_keyiterator' object has no attribute 'next'"

This method has been deleted in python 3?
 Why not use next(iter)?

or what should I do to fix it?
