### ISSUE TITLE
Pytorch Distributed DataParallel support

### ISSUE THREAD

**Issue by abhi-plusai** [median-research-group/LibMTL#16]
Hi, great work.

Did you guys try to run gradient surgery methods with distributed dataparallel in pytorch. I couldn't run it due to calling backwards multiple times creating gradient syncing issues in distributed learning

**Comment by Baijiong-Lin** [comment]
Hi, ``LibMTL`` now does not support DDP. We will add this support in the future.

**Comment by Baijiong-Lin** [comment]
Closed as no further updates.
