### ISSUE TITLE
Trainer.train()中的变量train_loss_buffer是怎么来的

### ISSUE THREAD

**Issue by gehaocool** [median-research-group/LibMTL#17]
https://github.com/median-research-group/LibMTL/blob/3928656aa6342cbc84b66948d7e798dd4946e471/LibMTL/trainer.py#L196 

self.model中并不总是有train_loss_buffer这个变量，只有GradNorm和DWA里面有

**Comment by Baijiong-Lin** [comment]
Closed as no further updates.
