### ISSUE TITLE
uw initialization

### ISSUE THREAD

**Issue by antct** [median-research-group/LibMTL#18]
Hi, I found that the value -0.5 was used when initializing the parameter in line 19 of uw.py. 
My doubt is why this value is not 0, since the variable loss_scale is equivalent to `log \sigma` in the original paper.
```python
self.loss_scale = nn.Parameter(torch.tensor([-0.5]*self.task_num, device=self.device))
```

**Comment by Baijiong-Lin** [comment]
The initialization here refers to [mtan](https://github.com/lorenmt/mtan/blob/master/im2im_pred/model_segnet_dense.py#L60). I think you can also use zero initialization.

**Comment by antct** [comment]
Thanks for your reply~
