### ISSUE TITLE
trainer can't work

### ISSUE THREAD

**Issue by Sakura4036** [median-research-group/LibMTL#19]
when I try to run this trainer , .next() can't run

-> "AttributeError: 'dict_keyiterator' object has no attribute 'next'"

I use:
python=3.7
torch=11.3

This method has been deleted in python 3?
Why not use next(iter)?

or what should I do to fix it?

![image](https://user-images.githubusercontent.com/42060616/202403974-5e1153a7-ac3d-4635-9489-ed88d5609198.png)
![image](https://user-images.githubusercontent.com/42060616/202404144-40281362-3e9b-4d69-a8e5-491230ba2094.png)

**Comment by Baijiong-Lin** [comment]
Please change torch from version 1.13 to 1.8. It can run.

**Comment by Sakura4036** [comment]
OK, thanks.  I can try it later.

**Comment by Sakura4036** [comment]
I change env to torch 1.8.0, still same error!
 
![image](https://user-images.githubusercontent.com/42060616/202604597-0eb67a52-c22f-4361-a2de-89e9209f8306.png)
![image](https://user-images.githubusercontent.com/42060616/202604664-c6076641-6357-4ea6-81f3-59ffbccb66ae.png)

**Comment by Baijiong-Lin** [comment]
What is your run command? Can you run the example like office-31 successfully?

**Comment by Sakura4036** [comment]
No, I can't , same error

![Uploading image.png…]()

**Comment by Sakura4036** [comment]
![image](https://user-images.githubusercontent.com/42060616/202615814-74abaf86-82a3-4dca-99a2-00b610ef2fd6.png)

**Comment by Baijiong-Lin** [comment]
Office-31 is a multi-input MTL problem where each task has its own input data, thus ``multi_input`` should be set as ``True`` as follows:
`python train_office.py --multi_input`

Please refer to [Docs](https://libmtl.readthedocs.io/en/latest/docs/user_guide/mtl.html) for more detail.

**Comment by Sakura4036** [comment]
it can run! 

I checked my Dataset and Dataloader, it's similar to the dataset used in LibMTL , it seems no problem

Then what other problems may cause this error？

**Comment by Baijiong-Lin** [comment]
Do you mean there is still an error when applying LibMTL to your own dataset? Have you defined your own Dataset and Dataloader correctly? Please refer to [Docs](https://libmtl.readthedocs.io/en/latest/docs/develop/dataset.html#) for the detail about applying LibMTL to a new dataset.

**Comment by Sakura4036** [comment]
OK，thanks， I will try it later
