### ISSUE TITLE
为啥没有使用GradNorm 等loss的例子 

### ISSUE THREAD

**Issue by xxllp** [median-research-group/LibMTL#2]
你好 我看代码里面有这些weighting 但是例子中没有使用 这块要使用的化 需要怎么设置呢 

代码里面没看到这些weight的相关代码

**Comment by Baijiong-Lin** [comment]
你好, 你可以参考我们的文档https://libmtl.readthedocs.io/en/latest/docs/user_guide/benchmark.html

**Comment by xxllp** [comment]
好的  我看代码里面这部分是模型吗 感觉有点不够情绪哈 是继承了还是直接一个类

>        class MTLmodel(architecture, weighting):
            def __init__(self, task_name, encoder, decoders, rep_grad, multi_input, device, kwargs):
                super(MTLmodel, self).__init__(task_name, encoder, decoders, rep_grad, multi_input, device, **kwargs)
                self.init_param()

**Comment by Baijiong-Lin** [comment]
这里是继承了两个类

**Comment by xxllp** [comment]
好的 我看懂了 不知道你这边例子是否有不同的weighting下的结果差别

**Comment by Baijiong-Lin** [comment]
你可以自己train一下, 或者参考一下相关文章report的结果

**Comment by xxllp** [comment]
thx
