### ISSUE TITLE
DataLoader errors when I set num_workers>1

### ISSUE THREAD

**Issue by alphabet-lgtm** [median-research-group/LibMTL#20]
I have found someone says set num_workers=0 will work,but it's too slow...My system is Ubuntu

Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f7c408fce60>
Traceback (most recent call last):
  File "/home/user/miniconda3/envs/IB/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1510, in __del__
    self._shutdown_workers()
  File "/home/user/miniconda3/envs/IB/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1493, in _shutdown_workers
    if w.is_alive():
  File "/home/user/miniconda3/envs/IB/lib/python3.7/multiprocessing/process.py", line 151, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process

**Comment by alphabet-lgtm** [comment]
Maybe tqdm is used in the code?

**Comment by Baijiong-Lin** [comment]
Could you provide more details to reproduce this bug? I set the num_workers [here](https://github.com/median-research-group/LibMTL/blob/main/examples/office/create_dataset.py#L46) as 2, and it can run normally.

**Comment by alphabet-lgtm** [comment]
I used examples of train_office and edit a little. I have changed train_dataloaders to my dataloader but it is still imported by torch.utils.data.DataLoader

**Comment by Baijiong-Lin** [comment]
Could you successfully run train_office.py if you set the num_workers [here](https://github.com/median-research-group/LibMTL/blob/main/examples/office/create_dataset.py#L46) as 2?

**Comment by alphabet-lgtm** [comment]
I haven't tried yet, but I will try after downloading the dataset. Will there any difference in using dataloaders of train_office.py?

**Comment by Baijiong-Lin** [comment]
Anyway, you need to provide enough details (such as environment, source code, running command, and so on) to help us to reproduce this bug. Otherwise, it is hard to find the problem just according to the error information. Thus, the most effective and efficient way is to test the examples we provided. If it is ok, maybe you have edited some code wrongly such as defining the new Dataloader with the wrong format.

**Comment by alphabet-lgtm** [comment]
OK, thank you, I will tell you the result after testing the examples.

**Comment by Baijiong-Lin** [comment]
Closed as no further updates.
