### ISSUE TITLE
Unable to save the trained model 

### ISSUE THREAD

**Issue by shubham166** [median-research-group/LibMTL#23]
When I try to save the trained model i.e. full model using the following command - 

`torch.save(model, "<path>") `

It throws this error 

`AttributeError: Can't pickle local object 'Trainer._prepare_model.<locals>.MTLmodel'`

**Comment by Baijiong-Lin** [comment]
I suggest using [LibMTL v1.1.6](https://github.com/median-research-group/LibMTL/tree/v1.1.6) which can save the best model automatically.

**Comment by Baijiong-Lin** [comment]
Closed as no further updates.
