### ISSUE TITLE
How to transfer to other projects.for example,yolov5

### ISSUE THREAD

**Issue by LeonNerd** [median-research-group/LibMTL#25]
hello,I need these structures or weighting strategies for yolov5, what should i do?

**Comment by Baijiong-Lin** [comment]
This [Docs](https://libmtl.readthedocs.io/en/latest/docs/develop/dataset.html) shows how to apply ``LibMTL`` to your own project.

**Comment by Baijiong-Lin** [comment]
Closed as no further updates.
