### ISSUE TITLE
Question about Cross stitch implementation

### ISSUE THREAD

**Issue by michalkovacik2** [median-research-group/LibMTL#28]
Hi, I would like to ask you question about the Cross Stitch implementation.
In your code you create cross_unit as torch.ones(4, self.task_num). So for each of the 4 resnet layers you have tensor of task_num values. For example with 2 tasks it would be tensor(4, 2) and each layer has a 1x2 cross unit. But in the paper in equation (1) for two tasks they have a matrix of 2x2. Is there a reason that you have a 1x2 cross unit, did I misunderstand something in the paper ?
![formula](https://user-images.githubusercontent.com/73242722/219868518-052f5324-efed-4b7d-8d41-90be0561db21.png)
https://github.com/median-research-group/LibMTL/blob/3928656aa6342cbc84b66948d7e798dd4946e471/LibMTL/architecture/Cross_stitch.py#L23-L35
Because I was expecting to see something like this in the implementation:
```python
self.cross_unit = nn.Parameter(torch.ones(4, self.task_num, self.task_num)) # matrix for each layer

def forward(self, inputs):
    s_rep = {task: self.resnet_conv[task](inputs) for task in self.task_name}
    ss_rep = {i: [0]*self.task_num for i in range(4)}
    for i in range(4):
        for tn, task in enumerate(self.task_name):
            if i == 0:
                ss_rep[i][tn] = self.resnet_layer[str(i)][tn](s_rep[task])
            else:
                cross_rep = sum([self.cross_unit[i-1][tn][j]*ss_rep[i-1][j] for j in range(self.task_num)]) # access matrix row of each task
                ss_rep[i][tn] = self.resnet_layer[str(i)][tn](cross_rep)
    return ss_rep[3]
```

**Comment by Baijiong-Lin** [comment]
Yep, I think that there indeed has some inconsistency between our implementation and the original paper. Thanks for your suggestion.
