### ISSUE TITLE
Issue with val Epoch and `self.base_result` 

### ISSUE THREAD

**Issue by ovshake** [median-research-group/LibMTL#29]
Hi, 
Thanks for open sourcing this wonderful repo. I have a question regarding the following line https://github.com/median-research-group/LibMTL/blob/d05c80c487bfc0036ed62f6dcd14730d1e46caa9/LibMTL/_record.py#L96, Shouldn't base result be updated here i.e. `self.base_result = new_result` else the improvement will always be compared over base_result, and we would not get the best checkpoint. I may be missing something, but the results on my experiments doesn't look correct to me. 
thanks

**Comment by Baijiong-Lin** [comment]
You can update the base result here but not necessary. Note that we compute the overall improvement between the candidate result and the base result, then choose the best result/model/checkpoint with the highest improvement.
https://github.com/median-research-group/LibMTL/blob/d05c80c487bfc0036ed62f6dcd14730d1e46caa9/LibMTL/_record.py#L94-L95
Thus if you update the base result, this line should be modified as `if improvement > 0`. But these two types of implementations are the same.

Whether you define the `task_dict` in the correct way, especially the `weight` item.
https://github.com/median-research-group/LibMTL/blob/d05c80c487bfc0036ed62f6dcd14730d1e46caa9/LibMTL/trainer.py#L51-L54

**Comment by Baijiong-Lin** [comment]
Closed as no further updates.
