### ISSUE TITLE
Wouldn't torch.randn in equal weighting give negative weights to half of the tasks?

### ISSUE THREAD

**Issue by sarthak-314** [median-research-group/LibMTL#3]

**Comment by Baijiong-Lin** [comment]
There is no torch.randn in the [EW](https://github.com/median-research-group/LibMTL/blob/main/LibMTL/weighting/EW.py) method.

**Comment by sarthak-314** [comment]
Sorry, I meant in RLW.
I am using tf.clip_by_value(0, 2) with tf.random.normal(mean=1, stddev=1) in my code.

**Comment by Baijiong-Lin** [comment]
> Sorry, I meant in RLW. I am using tf.clip_by_value(0, 2) with tf.random.normal(mean=1, stddev=1) in my code for positive weights centered around 1.

The RLW method uses the softmax function to normalize the task weights sampled from torch.randn to avoid negative weights. The torch implementation refers to [here](https://github.com/median-research-group/LibMTL/blob/main/LibMTL/weighting/RLW.py#L20).
