### ISSUE TITLE
Performance issue for NYUv2 

### ISSUE THREAD

**Issue by kcs6568** [median-research-group/LibMTL#31]
Thank you for your excellent contribution!

I have a question about the performance of MTAN with PCGrad.

In my experiment, the result of NYUv2 is very different from the PCGrad official performance (although I not used UW in this experiment)

![image](https://user-images.githubusercontent.com/42672895/228778069-ce64fb68-7b0f-403f-bbd9-8bc19091d69c.png)
(sorry for this image to very small)

Also, when I experimented to the resnet50-HPS without weighting method, the result is beyond the MTAN official performance.
![image](https://user-images.githubusercontent.com/42672895/228779875-49f5af17-9dd6-4815-a0d1-3e188676a2b7.png)

I tried your official training command line in all cases and used the dataset in your Dropbox.

Is that result the right phenomenon?

Thank you in advance!

**Comment by Baijiong-Lin** [comment]
The SegNet is used as the backbone network in the original PCGrad paper. While we use the DeepLabV3+ (ResNet50 with dilated convolution + ASPP) as the backbone here, which achieves better performance than SegNet.

**Comment by kcs6568** [comment]
Thank you for your answer!

Is there SegNet architecture in this library?

The SegNet is not in the LibMTL model directory.

Is not supported in the current version?

Or, is the same architecture when I tried the supported command-line below for the original MTAN with SegNet?
`python train_nyu.py --weighting DWA --arch MTAN --gpu_id 5 --scheduler step --train_bs 4`

**Comment by Baijiong-Lin** [comment]
LibMTL does not support the SegNet backbone network. MTAN is orthogonal to the backbone network, which means MTAN can combine with both SegNet and ResNet50.

**Comment by kcs6568** [comment]
Thank you!!
