### ISSUE TITLE
v1.1.6文档

### ISSUE THREAD

**Issue by DonnyLiu7** [median-research-group/LibMTL#33]
作者你好，不知道是否有v1.1.6的最新文档呢？我看新加的一些参数例如cfg等等都没有完整的例子与介绍，文档还是原来的版本

**Comment by DonnyLiu7** [comment]
我想加载自己的数据集，multi_inputs = True，存放格式是这样的：
- dataset
   - task_1
      -train
      -val 
   - task_2
      -train
      -val 
请问如何在v1.1.6的配置文件中的dataloader部分以正确的格式加载数据？

**Comment by DonnyLiu7** [comment]
我想加载自己的数据集，multi_inputs = True，存放格式是这样的：
    -dataset
       -task_1
        -train
        -val
       -task_2
        -train
        -val
        请问如何在v1.1.6的配置文件中的dataloader部分以正确的格式加载数据？

**Comment by DonnyLiu7** [comment]
我想加载自己的数据集，multi_inputs = True，存放格式是这样的：
-dataset
    -task_1
        -train
        -val
    -task_2
        -train
        -val
请问如何在v1.1.6的配置文件中的dataloader部分正确的加载数据？

**Comment by Baijiong-Lin** [comment]
你可以参考[OfficeDataset.py](https://github.com/median-research-group/LibMTL/blob/v1.1.6/LibMTL/dataset/OfficeDataset.py)来定制你的dataset，这个dataset文件定义了每个task在每个mode（train，val，test）下的dataset

**Comment by DonnyLiu7** [comment]
非常感谢
