### ISSUE TITLE
我想问问分支和主线的区别，另外我想问问是否计划实现ubernet

### ISSUE THREAD

**Issue by yushengjiexy** [median-research-group/LibMTL#37]
感觉还挺自豪的，谢谢你的工作

**Comment by Baijiong-Lin** [comment]
谢谢您的提问，branch v1.1.6的封装程度会比branch main的高。另外，请问ubernet是哪个方法，麻烦提供一下原文标题或者链接，谢谢您。

**Comment by yushengjiexy** [comment]
客气了，https://arxiv.org/pdf/1609.02132.pdf
UberNet : Training a ‘Universal’ Convolutional Neural Network for Low-, Mid-, and High-Level Vision using Diverse Datasets and Limited Memory

**Comment by Baijiong-Lin** [comment]
UberNet是为视觉感知任务定制化的结构，我们目前阶段更倾向于实现通用的多任务结构。后续我们会考虑实现这个方法，谢谢您的建议。

**Comment by yushengjiexy** [comment]
了解了
