### ISSUE TITLE
nashmtl修改更新次数后报错

### ISSUE THREAD

**Issue by yushengjiexy** [median-research-group/LibMTL#39]
我尝试了nashmtl,以下是我的vscode配置列表:
![image](https://user-images.githubusercontent.com/63044657/236612055-d2a35566-80eb-4623-9bf0-925dd938dce1.png)
我发现当我修改权重更新频率后,会报错如下:
![image](https://user-images.githubusercontent.com/63044657/236612039-e0c59b35-5c76-41cc-9dac-aa45a543aec8.png)

**Comment by Baijiong-Lin** [comment]
已修复

**Comment by yushengjiexy** [comment]
哥们，还是有报错的，alpha可能是numpy也可能是tensor

**Comment by Baijiong-Lin** [comment]
哪个配置下有报错，麻烦提供一下运行命令，谢谢

**Comment by yushengjiexy** [comment]
> 哪个配置下有报错，麻烦提供一下运行命令，谢谢

不好意思，是我看错了你的commit，修改错了，你的修改是ok的，已经没有报错了。另外，你能帮我看看我哦的bug吗，nashmtl算出来的weight_loss好小，是10-4级别的，是要调整什么超参数吗？谢谢

**Comment by Baijiong-Lin** [comment]
这个问题可能需要问一下Nash-MTL的作者们

**Comment by yushengjiexy** [comment]
> 这个问题可能需要问一下Nash-MTL的作者们

问了。但感觉，梯度很大时候，nashmtl就会计算出很小的loss权重(10-4)，反传回去时候网络参数的梯度就会非常小，整个网络根本迭代不动。

**Comment by Baijiong-Lin** [comment]
我也没想到什么好方法

**Comment by MingChaoXu** [comment]
> 下有报错，麻烦提供一下运行命令，谢



> > 这个问题可能需要问一下Nash-MTL的作者们
> 
> 问了。但感觉，梯度很大时候，nashmtl就会计算出很小的loss权重(10-4)，反传回去时候网络参数的梯度就会非常小，整个网络根本迭代不动。

请问，你这边用多任务算法的时候，有什么实际work的算法吗，我这边在实际使用的时候其实都会比单任务差很多

**Comment by MingChaoXu** [comment]
我这边主要是yolox架构的object detection跟自驾任务中的freespace，这两个任务，每个任务都有若干loss，但是用MTL来优化其实远比我随便调一下loss权重要差

**Comment by yushengjiexy** [comment]
@MingChaoXu 
你都试了哪些方法

**Comment by MingChaoXu** [comment]
我尝试了pcgrad，uw，nash mtl，cagrad，graddrop，都不好使，不知道你这有没有work的经验？

**Comment by yushengjiexy** [comment]
@MingChaoXu 
和nashmtl的作者聊的,可能要对输出做归一化,https://github.com/AvivNavon/nash-mtl/issues/13
你的nash mtl没问题吗

**Comment by MingChaoXu** [comment]
我这边nash mtl可以收敛，就是精度变差了，你有尝试别的算法吗？效果怎么样？

**Comment by yushengjiexy** [comment]
我就是pcgrad，有一点点效果，试了nashmtl不行，现在在尝试gradnorm，我也是用的yolox的主干。感觉可能和你的数据分布相关

**Comment by MingChaoXu** [comment]
我的两个任务的数据并没有共同标注，就是每份数据只有一个任务的标注，不知道这个会不会影响，因为我看论文里的数据好像是多任务标注都有的？

**Comment by yushengjiexy** [comment]
这不是非同源数据吗？

**Comment by yushengjiexy** [comment]
> 我尝试了pcgrad，uw，nash mtl，cagrad，graddrop，都不好使，不知道你这有没有work的经验？

![image](https://github.com/median-research-group/LibMTL/assets/63044657/4d00da99-2c4e-4537-abd8-ff8467045e69)

**Comment by MingChaoXu** [comment]
是的，可以说非同源数据吧，domain是一样的，只不过只有单个数据的标注，你的任务是两种标注都有是吗？

**Comment by yushengjiexy** [comment]
shide

**Comment by yushengjiexy** [comment]
谢谢作者，nashmtl这个方法我先不用了吧。。。。

**Comment by yushengjiexy** [comment]
> 是的，可以说非同源数据吧，domain是一样的，只不过只有单个数据的标注，你的任务是两种标注都有是吗？

可以看看这篇paper https://arxiv.org/pdf/2209.11379.pdf
另外，可以加下微信，讨论下吗，DayDayAmazing，备注mtl

**Comment by yushengjiexy** [comment]
@MingChaoXu

**Comment by MingChaoXu** [comment]
@yushengjiexy 好的～互相学习一下hhh，加你了
