### ISSUE TITLE
Time-series MTL

### ISSUE THREAD

**Issue by madhu-kt** [median-research-group/LibMTL#4]
Hi,

First of all, this is a fantastic library! Amazing work.

My question: can LibMTL can be used in time-series applications? I.e. do we only need to provide encoder/decoder architectures such as LSTMs? Would the loss-weighting methods need to be extended in any way? 
I'm fairly new to MTL, so pardon the naive question.

Thanks,
Madhu

**Comment by Baijiong-Lin** [comment]
Yes, you just need to provide appropriate encoder/decoder architectures to LibMTL according to your problem.

**Comment by madhu-kt** [comment]
Sounds good, thanks!
