### ISSUE TITLE
Saving and loading models

### ISSUE THREAD

**Issue by yamizi** [median-research-group/LibMTL#48]
Hello LibMTL team,
I went through your code, and I am not sure which part could be extended to support loading and saving the models to disk.
The model inside the Trainer is not picklable, and I was wondering if you could hint me to the components that would need to be saved and loaded for instance to resume training or postpone testing,
Best,
Salah

**Comment by Baijiong-Lin** [comment]
Please refer to https://github.com/median-research-group/LibMTL/issues/23.

**Comment by Baijiong-Lin** [comment]
v1.1.5 now supports saving and loading models.

**Comment by Baijiong-Lin** [comment]
Closed as no further updates.
