### ISSUE TITLE
Passing arguments to encoder/decoder constructors

### ISSUE THREAD

**Issue by madhu-kt** [median-research-group/LibMTL#5]
Is it possible to currently pass in arguments to initialize the encoders and decoders?
For example, given this linear encoder class:

```
class SimpleLinearEncoder(nn.Module):
    def __init__(self, n_features, n_hidden1, n_output):
        super(SimpleLinearEncoder, self).__init__()
        self.encoder = torch.nn.Sequential(
            torch.nn.Linear(n_features, n_hidden1),
            torch.nn.ReLU(),
            torch.nn.Linear(n_hidden1, n_output)
        )

    def forward(self, x):
        return self.encoder(x)
```
In order to create an encoder with 20 inputs, 10 neurons in the hidden layer and 4 outputs without setting them as default argument values, can we pass in these parameters to `kwargs`? E.g:

`kwargs = {"weight_args": {"alpha": 1.5}, "arch_args": {}, "n_features": 20, "n_hidden1": 10, "n_output": 4 }`

```
 model = Trainer(task_dict=task_dict,
                    weighting=weighting_method.__dict__[mtl_weighting_method],
                    architecture=architecture_method.__dict__[mtl_architecture],
                    encoder_class=SimpleLinearEncoder,
                    decoders=decoders,
                    rep_grad=False,
                    multi_input=True,
                    optim_param={'optim': 'sgd', 'lr': 0.005, 'weight_decay': 0.00005, 'momentum': 0.9},
                    scheduler_param={'scheduler': 'step', 'step_size': 100, 'gamma': 0.5},
                    **kwargs)
```
I wasn't able to get the above to work, and my naive guess is that it's because of these lines in the `LibMTL.architecture` classes, e.g. HPS:

`self.encoder = self.encoder_class()`

I'm new to PyTorch so perhaps I'm missing an easy solution.

Thanks.

**Comment by Baijiong-Lin** [comment]
``LibMTL`` does not support passing the arguments of encoder/decoder constructors to ``kwargs`` yet. 

Please refer to [doc](https://libmtl.readthedocs.io/en/latest/docs/develop/dataset.html) about how to use ``LibMTL`` to deal with a new MTL problem.
