### ISSUE TITLE
How to export saved models to other formats, such as onnx, mnn, etc

### ISSUE THREAD

**Issue by zcc720** [median-research-group/LibMTL#51]
Hello, first of all, thank you for your great work.
 I saved the best model while running the Office example, but I want to export this model as an ONNX model and use tools like Netron to understand the model structure. How can I add code to the framework? Can you add an exported component for exporting various models, such as onnx, mnn, tflite

**Comment by Baijiong-Lin** [comment]
Sorry, I am not familiar with ONNX. But LibMTL supports saving model now. Can't it be converted to ONNX like other torch models?

**Comment by Baijiong-Lin** [comment]
Closed as no further updates.
