### ISSUE TITLE
Questions about AlignMTL

### ISSUE THREAD

**Issue by DaPraxis** [median-research-group/LibMTL#52]
Hi there, I had a hard time reproducing the AlignMTL results. I am wondering if you have encountered the same issue? Have you guys evaluated AlignMTL under HPS?

Thanks,
Max

**Comment by Baijiong-Lin** [comment]
The reproduced result of AlignMTL is presented at https://github.com/median-research-group/LibMTL/blob/main/examples/nyu/results/segnet_results.pdf.

**Comment by DaPraxis** [comment]
Thanks, but isn't this in MTAN architecture?

**Comment by Baijiong-Lin** [comment]
Closed as no further updates.
