### ISSUE TITLE
Question about AlignedMTL

### ISSUE THREAD

**Issue by junyizeng** [median-research-group/LibMTL#57]
Thank you very much for updating Aligned MTL. After comparing your experiments with the paper, I have a question regarding the pseudocode in the first image. In the pseudocode, 'w' represents the weight for each loss function. However, in your code, you directly sum over 'B' in the 'alpha' code. I was wondering if you assume that the weights for each task are equal when writing the code?
![image](https://github.com/median-research-group/LibMTL/assets/80525097/cd83990d-0def-4079-9c56-5030aec581dc)
![image](https://github.com/median-research-group/LibMTL/assets/80525097/7f30b442-f434-4c8d-bf04-166e57dfaa68)

**Comment by Baijiong-Lin** [comment]
The original code of AlignedMTL does not use $\omega$ (refer to https://github.com/SamsungLabs/MTL/blob/master/code/optim/aligned/solver.py).

**Comment by Baijiong-Lin** [comment]
Closed as no further updates.
