### ISSUE TITLE
关于rep_grads参数的问题

### ISSUE THREAD

**Issue by junyizeng** [median-research-group/LibMTL#58]
您好，我重点看了一下您复现的MGDA方法，对于其中的rep_grads参数的作用不太清楚，结合论文，我猜测它的作用是将不同任务共享的参数与个任务单独的参数分离出来，然后MOO方法主要是求针对共享参数的梯度，请问我的理解是正确的吗？如果有误，希望能得到您的指正与说明。

**Comment by Baijiong-Lin** [comment]
``rep_grad=True``是指对shared **representation**求gradient作为task-specific gradient (即MGDA paper中的MGDA-UB方法)，``rep_grad=False``是指对shared **parameter**求gradient作为task-specific gradient (即原始的MGDA方法)。

我们的docs也有关于``rep_grad``的介绍和解释 (https://libmtl.readthedocs.io/en/latest/docs/user_guide/mtl.html#weighting-strategy)

**Comment by junyizeng** [comment]
非常感谢您的解答，我再结合您的说明文档理解一下。

**Comment by junyizeng** [comment]
那请问一下项目文件中是否有使用rep_grads的示例吗？

**Comment by Baijiong-Lin** [comment]
在运行命令加上``--rep_grad``就可以了

**Comment by Baijiong-Lin** [comment]
Closed as no further updates.
