### ISSUE TITLE
关于tabular数据的训练问题

### ISSUE THREAD

**Issue by itangxinyu** [median-research-group/LibMTL#59]
老师您好，请问LibMTL支持对表格数据的训练吗？应该修改哪些代码呢

**Comment by Baijiong-Lin** [comment]
可以参考https://libmtl.readthedocs.io/en/latest/docs/develop/dataset.html

**Comment by itangxinyu** [comment]
谢谢您的回答，但是我看到举的例子都是关于图像的例子，对于表格数据也是适用的吗？在example里哪一个例子和表格比较接近呢

**Comment by Baijiong-Lin** [comment]
理论上是可以的，但我没做过表格数据

**Comment by Baijiong-Lin** [comment]
Closed as no further updates.
