### ISSUE TITLE
Multi-input MTL

### ISSUE THREAD

**Issue by madhu-kt** [median-research-group/LibMTL#6]
Most of the research papers for the implemented architectures and weighting methods seem to deal with single-input-multi-output tasks such as simultaneous object detection and segmentation from a single image. However, `LibMTL` also supports multi-input tasks, where each task has its own data (e.g. MNIST where each digit has its own task-specific layers). Is there a set of research papers that discuss this approach? I'm curious to learn how `LibMTL` evaluates the loss in these situations. I can dig into the code to get a deeper understanding, but in the meantime, if there are papers that discuss this, it would really help to have some links (and maybe update the docs).

Thanks!

**Comment by Baijiong-Lin** [comment]
Many papers conduct experiments on those datasets with multi-input tasks. For example, the multilingual problems on the XTREME benchmark are used by [GradVac](https://openreview.net/forum?id=F1vEjWK-lH_) and [RLW](https://arxiv.org/abs/2111.10603). Moreover, we have provided a multi-input example in [examples/office](https://github.com/median-research-group/LibMTL/tree/main/examples/office).

**Comment by madhu-kt** [comment]
Thank you for the resources!
