### ISSUE TITLE
Image size of NYUv2 dataset should be 3*288*384

### ISSUE THREAD

**Issue by Xjh0327** [median-research-group/LibMTL#61]
The `README.md` in `./examples/nyu` says it's `3*284*384` while it should be `3*288*384.` :)

**Comment by Baijiong-Lin** [comment]
The NYUv2 dataset is pre-processed by [mtan](https://github.com/lorenmt/mtan).

**Comment by Xjh0327** [comment]
Yes, I've seen this. But in this paper it also says the image size is `3*288*384`. Setting `--img_size 3 284 384` will raise bug. Just a small typo in `README.md`. Thank you!
