### ISSUE TITLE
Inconsistency between formula and implementation in count_improvement function

### ISSUE THREAD

**Issue by Tyqfat** [median-research-group/LibMTL#65]
Dear Maintainers,
I have encountered a potential issue while reading and using the project. In the [LibMTL.utils](https://libmtl.readthedocs.io/en/latest/docs/_autoapi/LibMTL/utils/index.html#module-LibMTL.utils),  I believe there is an inconsistency between the mathematical formula for the count_improvement function and its implementation.
The formula is as follows:
![image](https://github.com/median-research-group/LibMTL/assets/100210376/4d881394-da40-4867-a300-d580d1852029)
However, I noticed that certain calculations in the code implementation do not entirely align with this formula. Specifically, here is where I think the inconsistency occurs: the denominator in the formula is N_{t,m}, while the denominator in the code when calculating the formula is B_{t,m}
![image](https://github.com/median-research-group/LibMTL/assets/100210376/f4bb4680-71b1-4056-8e4b-7ff9330f03cb)

**Comment by Baijiong-Lin** [comment]
There is a typo in the formula. The denominator $N_{t, m}$ should be $B_{t, m}$. Thanks for pointing out it.

**Comment by Tyqfat** [comment]
You're welcome. I'm glad to contribute to the project.
