### ISSUE TITLE
关于abstract_weighting.py中get_share_params的问题

### ISSUE THREAD

**Issue by wkgit88** [median-research-group/LibMTL#67]
作者您好，非常感谢您的工作，请问abstract_weighting.py第20行中self.get_share_params（）是需要自己根据不同的模型自己写吗？我好像没找到它的位置

**Comment by Baijiong-Lin** [comment]
https://github.com/median-research-group/LibMTL/blob/b1ff34d1bc72a208ef4f42301e6021db42913653/LibMTL/architecture/abstract_arch.py#L57

**Comment by wkgit88** [comment]
> https://github.com/median-research-group/LibMTL/blob/b1ff34d1bc72a208ef4f42301e6021db42913653/LibMTL/architecture/abstract_arch.py#L57

非常感谢您的回复
