### ISSUE TITLE
Support for Nash-MTL

### ISSUE THREAD

**Issue by AvivNavon** [median-research-group/LibMTL#7]
Thanks for this great repo, it is very useful!

Could you please add support for the Nash-MTL method described in the paper "Multi-Task Learning as a Bargaining Game"?

Paper: https://arxiv.org/abs/2202.01017
Official code: https://github.com/AvivNavon/nash-mtl

Thanks

**Comment by Baijiong-Lin** [comment]
Thank you for your advice and excellent work. We will add it to the next version of LibMTL.

**Comment by AvivNavon** [comment]
That's great, thank you.

**Comment by AvivNavon** [comment]
Hi, any updates on the timeline for this? I'm also happy to open a pull request for this.
Just to update, our paper was accepted to ICML 2022 so I think this would be a good addition to the repo.

**Comment by Baijiong-Lin** [comment]
Congratulation. We have added support for Nash-MTL. Thank you for your enthusiasm.

**Comment by AvivNavon** [comment]
That's great. Thank you for this great and important repo.

**Comment by yushengjiexy** [comment]
你好
