### ISSUE TITLE
Question about my understanding of aligned-MTL

### ISSUE THREAD

**Issue by HelloWorldLTY** [median-research-group/LibMTL#70]
Hi, thanks for your great work. I have a quick question about the principle of this paper (aligned-MTL)

https://openaccess.thecvf.com/content/CVPR2023/papers/Senushkin_Independent_Component_Alignment_for_Multi-Task_Learning_CVPR_2023_paper.pdf

It seems that your implementation of algorithm 1 will return alpha, and here my understanding is we can directly replace the gradient matrix G with G\alpha. Is it different from your diagram?

![image](https://github.com/median-research-group/LibMTL/assets/43333475/8719e0da-0ea9-4bc5-9100-4d0032fd1949)

If my understanding is incorrect, how to combine this component to my own dataset? It is a tarbular one and just simple regression tasks.

**Comment by Baijiong-Lin** [comment]
In our re-implementation, $\alpha$ will affect the update of task-specific parameters, following official implementation of Aligned-MTL.

**Comment by HelloWorldLTY** [comment]
OK, thanks a lot. I also have a question about multi-task learning. If my model performs well for 2 out of 3 tasks, but very bad in the third task (say, pearson correlation <0), and under this case, do you think using gradient alignment can significantly improve the model performance? Thanks.

**Comment by Baijiong-Lin** [comment]
I think you can try it, maybe it will be useful.

**Comment by HelloWorldLTY** [comment]
Thanks. Furthermore, could we directly use callback to set up early stop in the training process? Thanks.

**Comment by Baijiong-Lin** [comment]
No, LibMTL does not support callback.

**Comment by Baijiong-Lin** [comment]
Closed as no further updates.
