### ISSUE TITLE
Aligned-MTL-UB Efficient version

### ISSUE THREAD

**Issue by azj-n** [median-research-group/LibMTL#73]
Hello, will you be adding the efficient Aligned-MTL-UB version where they use representation instead of gradient calculation? Thank you

**Comment by Baijiong-Lin** [comment]
Sure. If adding ``--rep_grad`` in the training command, it means computing the gradient w.r.t the shared representation instead of shared parameters.

**Comment by azj-n** [comment]
I see, thank you.
