### ISSUE TITLE
Question regarding the results in Table 1 of the paper

### ISSUE THREAD

**Issue by IdanAchituve** [median-research-group/LibMTL#75]
Hi,
Thanks for this great repository. 
Regarding the reported results in Table 1, did you take the best test values across training or the test values at the end of training? If it is the former, what metric did you use to chose the best model?

Thanks,
Idan

**Comment by Baijiong-Lin** [comment]
We choose the best model on the validation dataset (or the test dataset if there is no validation dataset) in terms of $\Delta_p$ (a commonly used overall performance metric in multi-task learning, https://github.com/median-research-group/LibMTL/blob/main/LibMTL/utils.py#L48)

**Comment by IdanAchituve** [comment]
Great, thanks.
