### ISSUE TITLE
训练效果会受到epoch大小的影响吗，我只有一个任务同时使用6个loss，想看一下效果

### ISSUE THREAD

**Issue by entuo** [median-research-group/LibMTL#76]

**Comment by entuo** [comment]
还有一个问题，这个train_loss_buffer到底是如何更新的。self.model.train_loss_buffer[:, epoch] = self.meter.loss_item在train中

**Comment by Baijiong-Lin** [comment]
> 训练效果会受到epoch大小的影响吗

不同数据集的情况可能不一样，建议你自己尝试一下

> 还有一个问题，这个train_loss_buffer到底是如何更新的。self.model.train_loss_buffer[:, epoch] = self.meter.loss_item在train中

每个epoch的平均loss

**Comment by entuo** [comment]
谢谢您的答复
