### ISSUE TITLE
QM9 applicability of the architectures

### ISSUE THREAD

**Issue by PaoloBonettiPolimi** [median-research-group/LibMTL#77]
Hi guys, thank you for your work! I have a question regarding the QM9 dataset: all the architectures that are not based on HPS require a resnet or an image, leading to an error when the "main.py" is called for any of them. Am I wrong? Do you have any variant of the "main.py" that works for the QM9 dataset with the other architectures?

**Comment by Baijiong-Lin** [comment]
Yes, you are right. Actually, there are very few general architectures in multi-task learning.
