### ISSUE TITLE
请教一下Weighting中梯度计算的一些问题

### ISSUE THREAD

**Issue by Ruizhuo-Xu** [median-research-group/LibMTL#78]
<img width="832" alt="image" src="https://github.com/median-research-group/LibMTL/assets/110621793/50a89278-eba2-4965-b5f8-faa80e323baa">
请教一下图中这两种计算梯度的方式分别有什么优劣吗（显存或者计算速度）？

**Comment by Baijiong-Lin** [comment]
backward会自动计算task-specific parameter的gradient并存储在tensor.grad里，在optimizer.step()会自动更新task-specific parameter的参数

autograd只会计算share parameter的gradient并且不会存储在tensor.grad里而是直接返回gradient

在weighting的实现中，可以根据不同的需求去选择这两个方式
