### ISSUE TITLE
Wrong condition

### ISSUE THREAD

**Issue by VolodymyrVozniak** [median-research-group/LibMTL#8]
https://github.com/median-research-group/LibMTL/blob/70f0f00140d06c380e2ddbfbde6ab07ab2cdff20/LibMTL/_record.py#L63

`if epoch == 0 and self.base_result is None and mode==('val' if self.has_val else 'test'):` should be

**Comment by Baijiong-Lin** [comment]
That's right. We have fixed this problem. Thank you!
