### ISSUE TITLE
May I ask if you can reproduce MTAdam？

### ISSUE THREAD

**Issue by HuangZR-stu** [median-research-group/LibMTL#82]

**Comment by Baijiong-Lin** [comment]
There is an official implementation: https://github.com/ItzikMalkiel/MTAdam

**Comment by HuangZR-stu** [comment]
I don't know why I called his optimizer of MTAdam directly, but my model has no trace of training， even if I change the gradient

**Comment by Baijiong-Lin** [comment]
I suggest you discuss this with the authors of MTAdam.
