### ISSUE TITLE
rep_grad 适配在multi_input情况下所有weighting方法吗？

### ISSUE THREAD

**Issue by hungsing92** [median-research-group/LibMTL#83]
你好，非常感谢你的工作，收益良多！

有个问题想请教一下，在multi_input情况下，设置rep_grad的话我看代码会对不同task的encoder输出feature进行缓存，并且detach后送入decoder，有些weighting方式直接对loss进行weighting然后backward，按我的理解，梯度应该只到达刚刚detach的encoder feature那，这样encoder是不是没有更新？另外有些weighting方法是做了两次backward的，如MGDA，这样encoder应该是能更新的。

所以rep_grad在multi_input情况下适配所有weighting方法吗？

**Comment by Baijiong-Lin** [comment]
rep_grad只适用于部分gradient-based的weighting方法
