### ISSUE TITLE
关于class Trainer的问题

### ISSUE THREAD

**Issue by LPHFAQ** [median-research-group/LibMTL#84]
你好！非常感谢你的工作！我正在尝试将LibMTL应用在3D GAN Inversion的微调实验上，trainer.py的class Trainer中的train()方法的这个部分我没能理解，请问第一个框中调用的self.model.train()是什么？结合nyu例子的上下文我并未找到对应的实现。
此外，第二个框中的self.model.backward()如果我没理解错的话应该是调用的各个weighting strategy类的backward()方法？（例如EW.py的class EW的backward()）
![image](https://github.com/user-attachments/assets/fde90d23-d9bf-4fde-b292-7e6fc106a26e)
因为我的实验需求和给出的实例有较大的差异，所以需要通过阅读源码进行针对性的定制，后续也可能会有其他问题会请教你，很抱歉打扰到你

**Comment by Baijiong-Lin** [comment]
> 请问第一个框中调用的self.model.train()是什么？

https://pytorch.org/docs/stable/generated/torch.nn.Module.html#torch.nn.Module.train

> 第二个框中的self.model.backward()如果我没理解错的话应该是调用的各个weighting strategy类的backward()方法？

是的

**Comment by LPHFAQ** [comment]
> > 请问第一个框中调用的self.model.train()是什么？
> 
> https://pytorch.org/docs/stable/generated/torch.nn.Module.html#torch.nn.Module.train
> 
> > 第二个框中的self.model.backward()如果我没理解错的话应该是调用的各个weighting strategy类的backward()方法？
> 
> 是的

刚刚我是在静态地读代码所以第一个问题没能理解，我再试试调试一下nyu的实例看下能不能理解吧

**Comment by LPHFAQ** [comment]
> > 请问第一个框中调用的self.model.train()是什么？
> 
> https://pytorch.org/docs/stable/generated/torch.nn.Module.html#torch.nn.Module.train
> 
> > 第二个框中的self.model.backward()如果我没理解错的话应该是调用的各个weighting strategy类的backward()方法？
> 
> 是的

调试的时候发现self.model.train()这一步不能步进，应该是直接skip了，这是否是一个不需要的语句？

**Comment by Baijiong-Lin** [comment]
请仔细阅读 https://pytorch.org/docs/stable/generated/torch.nn.Module.html#torch.nn.Module.train

**Comment by LPHFAQ** [comment]
> 请仔细阅读 https://pytorch.org/docs/stable/generated/torch.nn.Module.html#torch.nn.Module.train

是我的低级错误。。。谢谢解答！
