### ISSUE TITLE
关于自己的任务上的一些疑问

### ISSUE THREAD

**Issue by Kami-chanw** [median-research-group/LibMTL#86]
我在处理一个transformer，想要实现grad norm。
我通过某种方式为每一层ffn的输出都计算了一个loss。这意味着第i层的loss依赖于前i-1层的参数。在这种情况下，share parameter应该如何选择？

**Comment by Kami-chanw** [comment]
我怕我写炸了 QAQ
可不可以推荐一个能快速实现、效果好、尽量别操作grad的dynamic loss weight方法？比如Dynamic Weight Average (DWA)这种（但是听说DWA对loss数量级差距大的场景不太好）。我这里其实是在每一层搞了个mse loss，虽然每一层加起来的平均值很小，大概是）0.01这个数量级，但是尤其是在初期很不稳定。

**Comment by Baijiong-Lin** [comment]
试试log loss
https://arxiv.org/pdf/2308.12029

**Comment by Kami-chanw** [comment]
非常感谢，请问您的这个工作有代码吗

**Comment by Baijiong-Lin** [comment]
https://github.com/median-research-group/LibMTL/blob/main/LibMTL/weighting/DB_MTL.py

**Comment by Kami-chanw** [comment]
我还有一个问题是，在有accumulate grad的情况下，需要额外做一些什么处理呢

**Comment by Baijiong-Lin** [comment]
不是操作grad的方法应该影响不大吧

**Comment by Kami-chanw** [comment]
这里不是修改了grad吗
https://github.com/median-research-group/LibMTL/blob/45705f2dbc6118b07ff78dfc6425cacf47c8f740/LibMTL/weighting/DB_MTL.py#L37

**Comment by Kami-chanw** [comment]
那么在我的场景中，我只需要对loss全部取一个log就可以了吗？（但是感觉全部取log和不取应该是一样的吧

**Comment by Baijiong-Lin** [comment]
那肯定是每个loss都log

**Comment by Kami-chanw** [comment]
好的。其实我除了每一层都有一个mse loss之外，还在transformer的最后一层有一个language modelling loss。我是否需要先对每一层的loss全部取log相加除以N，然后再加上log lm_loss ? 即
```math
\mathcal{L} =\log \mathcal{L}_{lm} +  \frac{1}{N}\sum_{i=1}^N \log \mathcal{L}^{(i)}_{mse}
```
另外我之前 lm_loss其实是有一个系数的，是不是取了对数之后就不需要这个系数了？

**Comment by Baijiong-Lin** [comment]
这你只能调一调看看了

**Comment by Kami-chanw** [comment]
如果loss比较小，会不会导致log之后负的特别厉害呀

**Comment by Baijiong-Lin** [comment]
你可以在loss上加一个很小的eps常数。另外，我只是根据我的经验去建议，并不能保证log loss在任何场景下都有效，你最好还是自己先试试看效果再说

**Comment by Kami-chanw** [comment]
看起来不太行，取log之后直接inf了

**Comment by Baijiong-Lin** [comment]
那你试试其他方法吧，我也不清楚你具体的场景是什么

**Comment by Kami-chanw** [comment]
> 试试log loss https://arxiv.org/pdf/2308.12029

论文里算法1的第(9)步，有考虑过使用softmax来normalization吗

**Comment by Kami-chanw** [comment]
这里看起来和论文的实现不太一致？另外如果sigma是负数，岂不是会导致loss本身变成负数？
https://github.com/median-research-group/LibMTL/blob/45705f2dbc6118b07ff78dfc6425cacf47c8f740/LibMTL/weighting/UW.py#L18-L24

**Comment by Baijiong-Lin** [comment]
哪个地方不一致？网络参数的更新是看梯度，loss的正负并不影响吧

**Comment by Kami-chanw** [comment]
首先是初始化为-0.5就有点奇怪诶，然后根据下图公式来看，正确的写法应该是`losses / (2* loss_scale.exp()**2) + loss_scale.log()`
![image](https://github.com/user-attachments/assets/e3411ccc-02ca-41d2-a810-338bdbce2cc7)

**Comment by Baijiong-Lin** [comment]
<img width="359" alt="image" src="https://github.com/user-attachments/assets/9fd16aca-e87c-4ffb-8886-9cce1dcefab4">

**Comment by Kami-chanw** [comment]
这是出自于哪一篇论文呢

**Comment by Kami-chanw** [comment]
噢噢不好意思，刚才pdf搜索的时候没有找到。那关于它的初始值呢，为什么初始为-0.5?

**Comment by Baijiong-Lin** [comment]
初始的时候会比较接近1

**Comment by Kami-chanw** [comment]
那我把它初始化为log(1/2)，`1/(2*loss_scale.exp())`直接就是1了，岂不是更好吗
