### ISSUE TITLE
potential bug about "same_rep"

### ISSUE THREAD

**Issue by windrises** [median-research-group/LibMTL#9]
https://github.com/median-research-group/LibMTL/blob/5566bf1b4593c619f48c0596ac4fdedfba7fcbba/LibMTL/architecture/abstract_arch.py#L48
It seems to me that the variable "same_rep" should be "False" if the variable "s_rep" is a list.

**Comment by Baijiong-Lin** [comment]
Yes. We have fixed this bug. Thank you.
